# debug: true #DEBUG Máximo da aplicação, exibe execução do Maven também

cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.promptuscd.com.br

spring:
  application:
    name: springBoot_curso_0_a_AWSeGCP
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_curso_0_a_awsegcp?useTimezone=true&serverTimezone=UTC
    username: root
    password: Gu021204$
  jpa:
    show-sql: true
    format_sql: true
    open-in-view: false
    hibernate:
#     ddl-auto: update *DEFAULT Hibernate
#     ddl-auto: none *PROFESSOR UTILIZOU ESSA ABORDAGEM
      ddl-auto: validate #RECOMENDAÇÃO DO CLAUDE (Hibernate verificará se o schema/db bate com as entidades relacionadas)
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    #root: WARN
    br.com.beltsistemas: DEBUG #INFO é o default
    org:
      flywaydb: DEBUG
#      springframework:
#        web: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/** # Definindo o path que será documentado pelo Swagger, ou seja, endpoints com /api/qualquer_coisa/v1/qualquer_coisa serão documentados
  swagger-ui:
    use-root-path: true # Para que o Swagger UI seja exibido na raiz do projeto, ou seja, http://localhost:8080/swagger-ui/index.html